name: Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Test Suite
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite, bcmath, intl, gd, exif, iconv
        coverage: none
    
    - name: Get Composer Cache Directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
    
    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-
    
    - name: Install Composer Dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install NPM Dependencies
      run: npm ci
    
    # Step 1: PHP_CodeSniffer
    - name: Run PHP_CodeSniffer
      run: vendor/bin/phpcs
    
    # Step 2: PHPStan
    - name: Run PHPStan
      run: vendor/bin/phpstan analyse --memory-limit=512M
    
    # Step 3: ESLint
    - name: Run ESLint
      run: npm run lint
    
    # Step 4: Pest
    - name: Run Pest Tests
      run: vendor/bin/pest
    
    # Step 5: Jest
    - name: Run Jest Tests
      run: npm test
    
    # Step 6: Dusk (disabled in CI by default due to browser dependencies)
    # Uncomment the following section if you want to run Dusk in CI
    # You'll need to set up a browser driver and configure it properly
    
    # - name: Install Chrome Driver
    #   run: |
    #     wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    #     echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google.list
    #     sudo apt-get update
    #     sudo apt-get install -y google-chrome-stable
    #     CHROME_VERSION=$(google-chrome --version | cut -d ' ' -f3 | cut -d '.' -f1)
    #     wget https://chromedriver.storage.googleapis.com/$(wget -q -O - https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION})/chromedriver_linux64.zip
    #     unzip chromedriver_linux64.zip
    #     sudo mv chromedriver /usr/local/bin/
    #     sudo chmod +x /usr/local/bin/chromedriver
    
    # - name: Run Laravel Dusk
    #   run: |
    #     php artisan serve --no-reload &
    #     php artisan dusk
